In [2]:
from string import punctuation
from re import sub
import pandas as pd

## Дистрибуция во всему IAVD

In [3]:
iavd = pd.read_csv('all_iavd.csv')

In [4]:
# переведем в нижний регистр
iavd['entry'] = iavd['entry'].str.lower()

# удалим случаи, когда отдельно основа и корень
iavd = iavd[~iavd['entry'].str.endswith('-')]

### Слова с гортанной смычкой

In [5]:
iavd_words = iavd['entry']
iavd_words_with_gs = iavd_words[iavd_words.str.contains('ʔ')]

Всего входов с гортанной смычкой:

In [6]:
len(iavd_words_with_gs)

844

Два раза гортанная смычка:

In [7]:
# два раза гортанная смычка
iavd_words_with_gs.str.contains('ʔ.+ʔ').sum()

np.int64(30)

Три раза:

In [7]:
iavd_words_with_gs[iavd_words_with_gs.str.contains('ʔ.+ʔ.+ʔ')]

Series([], Name: entry, dtype: str)

Всего 844+30=874 гортанных смычки

#### Обработка двойных

Каждый вход с двумя гортанными смычками раздваиваем и одно из ее появлений меняем на GS чтобы правильно считать дистрибуцию

In [8]:
iavd_double_gs = iavd_words_with_gs[iavd_words_with_gs.str.contains('ʔ.+ʔ')]
iavd_words_with_gs_corrected = iavd_words_with_gs[~iavd_words_with_gs.str.contains('ʔ.+ʔ')]
iavd_words_with_gs_corrected = pd.concat((iavd_words_with_gs_corrected, iavd_double_gs.apply(lambda x: sub(r'(ʔ.+)ʔ', r'\1GS', x))))
iavd_words_with_gs_corrected = pd.concat((iavd_words_with_gs_corrected, iavd_double_gs.apply(lambda x: sub(r'ʔ(.+ʔ)', r'GS\1', x))))

In [9]:
iavd_words_with_gs_corrected

14         авазэʔԓкас
38         автобусаʔн
45         авэлаʔԓкас
55          азлаʔԓкас
69           айванʔан
            ...
5647    ӽэGSлучэʔԓкас
5903     чэGSнӈэʔԓкас
6975     элGSэлэʔԓкас
7263      эGSрумʔэрум
7271       ˚аGSасхаʔн
Name: entry, Length: 874, dtype: str

Всего вхождений гортанной смычки:

In [10]:
LEN = len(iavd_words_with_gs_corrected)
LEN

874

### Что после гортанной смычки

Сонанты:

In [ ]:
iavd_words_with_gs_corrected.str.contains('ʔ[нймњӈлрљв]').sum() / LEN

np.float64(0.32036613272311215)

Гласные:

In [ ]:
iavd_words_with_gs_corrected.str.contains('ʔ[аиуоәэые]').sum() / LEN

np.float64(0.23684210526315788)

ԓ:

In [13]:
iavd_words_with_gs_corrected.str.contains('ʔԓ').sum() / LEN

np.float64(0.32379862700228834)

Посмотрим что встречается с ԓ:

In [14]:
pd.options.display.max_rows = 300
iavd_words_with_gs_corrected[iavd_words_with_gs_corrected.str.contains('ʔԓ')]

14            авазэʔԓкас
45            авэлаʔԓкас
55             азлаʔԓкас
79           айтатэʔԓкас
95            аӄтӽэʔԓкас
114        алупткʼаʔԓкас
116        алускʼваʔԓкас
120           алхпаʔԓкас
124      аләскʼваʔԓаткас
126        аләскʼваʔԓкас
153      ампәлсхэнаʔԓкас
161         ампэлаʔԓкаԓӽ
162          ампэлаʔԓкас
183         анањчпаʔԓкас
196            анзаʔԓкас
198          анзаʔԓсткас
205       анӄэӄчʼоʔԓкаԓӽ
218          ансаваʔԓкас
220          ансоӈаʔԓкас
237            ансэʔԓкас
238           ансэʔԓкиԓӽ
239            ансэʔԓкэс
240            ансэʔԓном
242          ансэʔԓэткас
247           анфчоʔԓкас
250          анхтзоʔԓкас
254          анхчоʔԓкаԓӽ
257         анчанзоʔԓкас
261        анәњчхчаʔԓкас
262       анәњчхчаʔԓкиԓӽ
263        анәњчхчаʔԓном
266        анэкстʼаʔԓкас
267         анэчпаʔԓкиԓӽ
272           ањԓнэʔԓкас
273          ањԓнэʔԓкиԓӽ
279            ањԓоʔԓкас
280           ањԓоʔԓкнэн
284     ањԓэнмайаӈаʔԓкас
316            аӈйаʔԓкас
384        атԓэмкʼаʔԓкас
507            босэʔԓкас
526            бусэʔԓкас
536            бэљэʔԓкас
549            валэʔԓкас
562            ваӈэʔԓкас
685               вэʔԓно
694           гладэʔԓкас
702           гордэʔԓкас
714           громэʔԓкас
729            дойэʔԓкас
735          дороваʔԓкас
736            дорэʔԓкас
752         дьэковаʔԓкас
757          дэвоваʔԓкас
760          дэзурэʔԓкас
764            дэљэʔԓкас
773        завидоваʔԓкас
776          задаваʔԓкас
786          запасаʔԓкас
787           запасаʔԓэс
795            зарэʔԓкас
798         застудэʔԓкас
804           звонэʔԓкас
819         знакомэʔԓкас
851          зэмоваʔԓкас
858            зэстаʔԓас
860              зэʔԓкас
889           иислуʔԓнэӈ
895           ийакэʔԓкас
925        икʼсхулэʔԓкас
998           имзатэʔԓэс
1009          имсӄʼэʔԓки
1020         инзилэʔԓкас
1036         инԓилуʔԓкас
1066         инсхэʔԓкиԓӽ
1068        инткитэʔԓкас
1073          интнэʔԓкас
1079        интхәлэʔԓкас
1090      интәнмувэʔԓкас
1092        интәнмэʔԓкас
1112         инчилэʔԓкас
1116        инәмтлэʔԓкас
1120      инәнкʼзуʔԓкиԓӽ
1122         инәнлуʔԓкас
1183           иткэʔԓкас
1244               иʔԓуӄ
1285         йасаӄаʔԓкас
1469         кихплэʔԓкас
1491        клэлхчэʔԓкас
1612           конэʔԓкас
1616      коњԓэԓтваʔԓкас
1634           косэʔԓкас
1635           косэʔԓном
1681         крэстэʔԓкас
1690         кскозоʔԓкас
1888           кэлэʔԓкас
1889          кэлэʔԓкнэн
2017          кʼулэʔԓкас
2037         кʼэквиʔԓкэс
2071         ӄазалаʔԓкас
2252          ӄэвчэʔԓкас
2273          ӄэӄчʼоʔԓэс
2341         ӄэчʼэԓэʔԓэс
2365        ладускаʔԓкас
2417         локавэʔԓкас
2422           лоӈаʔԓкас
2508           ләмәʔԓкас
2562           лэчэʔԓкас
2592           љэчэʔԓкас
2593          љэчэʔԓкнэн
2630        ԓваԓтэʔԓкаԓӽ
2697              ԓиʔԓэс
2919            ԓэʔԓфкас
2932           макоʔԓкас
2933            макоʔԓэс
2971             маʔԓкас
2972              маʔԓэс
3012          мәлвэʔԓкас
3038           мэњаʔԓкас
3092           наԓэʔԓкас
3109       нанчʼаӈаʔԓкас
3146           новаʔԓном
3170           нонэʔԓкас
3172           ноӈкаʔԓэс
3174         ноӈӄаʔԓэтэс
3214         ныкԓфаʔԓкас
3216       ныкумсалаʔԓэс
3225       ныкʼопӈэʔԓкас
3261          нытʼиʔԓкас
3265         нәкʼзуʔԓкас
3267         нәӄвлаʔԓкас
3273          нәмсхуʔԓэс
3280         нәнстәʔԓкас
3282        нәнтхлаʔԓкас
3287      нәптәԓаваʔԓкас
3291         нәсхлэʔԓкас
3297          нэвлсэʔԓэс
3301          нэвнэʔԓкас
3314           нэзэʔԓкас
3327        нэԓчэтэʔԓкас
3328          нэԓчэʔԓкас
3333     нэмчʼкʼэлэʔԓкас
3347           нэӈэʔԓкас
3348           нэӈэʔԓном
3370         ӈинсхэʔԓкас
3420          ӈэсчэʔԓкас
3427          обэдаʔԓкас
3433            оваʔԓкас
3478            олоʔԓкас
3537         опоздаʔԓкас
3556         отказаʔԓкас
3566          отхпаʔԓкас
3574          отэкаʔԓкас
3637           пахаʔԓкас
3669         пилэзаʔԓкас
3676         пињԓфаʔԓкас
3687         пиӈԓфаʔԓкас
3724            плэʔԓкас
3782          постаʔԓкас
3791        прибавэʔԓкас
3795       промосљаʔԓкас
3804         простэʔԓкас
3807        профэтаʔԓкас
3808        профэтаʔԓном
3877           пэлэʔԓкас
3900           пэтэʔԓкас
3901            пэтэʔԓэс
3909           пэчэʔԓкас
3974           рэӈоʔԓкас
3977         рэсоваʔԓкас
4006           саљэʔԓкас
4025           сатаʔԓкас
4038          сватаʔԓкас
4163          сӈачэʔԓкас
4177         сойэтэʔԓкас
4182         соӄэчэʔԓкас
4197           сољаʔԓкас
4198            сољаʔԓэс
4202            соԓаʔԓэс
4230         спасаʔԓкаԓӽ
4231          спасаʔԓкас
4239          спорэʔԓкас
4252          стараʔԓкас
4279          стэраʔԓкас
4281            стэʔԓкас
4282             стэʔԓэс
4359         сӽэтԓэʔԓкас
4399           сэйаʔԓкас
4409          сэлӄаʔԓкас
4457         таволаʔԓкас
4474           таӄаʔԓкас
4475           таӄаʔԓном
4648         тозазоʔԓкас
4656           тозаʔԓкас
4658        токтонаʔԓкас
4662        токтоӈоʔԓкас
4665         толкʼаʔԓном
4686          тормаʔԓкас
4688         тороваʔԓкас
4710          трубэʔԓкас
4854             тӽаʔԓэс
5058              тэʔԓэс
5060            тэʔԓэтэс
5143          убэраʔԓкас
5286           фиӈиʔԓкас
5329            фсэʔԓкас
5339             фчоʔԓэс
5358          фэкʼаʔԓкас
5564          ӽамԓӽэʔԓэс
5631            ӽэлаʔԓэс
5634         ӽэлучиʔԓкас
5662           чаӄаʔԓкас
5663            чаӄаʔԓэс
5771           чкʼэʔԓкас
5821          чфкраʔԓкас
5839         чхчаваʔԓкас
5896          чэстэʔԓкас
5926      чʼасфкраʔԓкаԓӽ
5940         чʼвэнэʔԓкас
5993          чʼовэʔԓкас
6006          чʼонэʔԓкас
6067             чʼэʔԓэс
6283          әнзлэʔԓкас
6299           әнкаʔԓкас
6346        әнкәмӈаʔԓкас
6428        әнӄэчэсэʔԓэс
6443        әнӄʼэфсэʔԓэс
6452            әнлоʔԓэс
6457            әнлуʔԓэс
6459          әнлуʔԓэтэс
6462          әнԓаʔԓэтэс
6490           әнԓчэʔԓэс
6492         әнԓчэʔԓэтэс
6527          әнпиӈэʔԓэс
6529        әнпиӈэʔԓэтэс
6533           әнпнэʔԓэс
6541         әнпәлсаʔԓэс
6558        әнросхӈаʔԓэс
6580          әнслуʔԓкас
6594         әнспасаʔԓэс
6652           әнткэʔԓэс
6689          әнтхзоʔԓэс
6708          әнтӽзоʔԓэс
6709        әнтӽзоʔԓэтэс
6735          әнтʼлэʔԓэс
6740        әнтʼонмэʔԓэс
6744        әнтʼэзлэʔԓэс
6764           әнфтэʔԓэс
6795          әнчоʔԓатэс
6797            әнчоʔԓэс
6827            әњԓаʔԓэс
6886         әӈӄсхэʔԓном
6968          элфԓэʔԓкас
6973            элэʔԓкас
6989       эԓхэњчкэʔԓкас
6990     эԓхэњчкэʔԓэткас
7048        энскэтэʔԓкас
7051          энсхэʔԓкас
7052         энсхэʔԓкиԓӽ
7053          энсхэʔԓном
7086         энхтзоʔԓкас
7091       энәнкʼзоʔԓкас
7112          эпԓӄэʔԓкас
7115          эпԓӽэʔԓкас
7119          эпстоʔԓкас
7219             эчэʔԓэс
7221           эчэʔԓэтэс
7328          ˚наԓэʔԓкас
7360          ˚таӄаʔԓкас
7361          ˚таӄаʔԓном
1414     кбарабанэʔԓGSан
1503         кљэчэʔԓGSин
1808          кчʼэʔԓGSин
1931        кʼансэʔԓGSан
1932    кʼанхтʼԓӈаʔԓGSан
1933       кʼанхчоʔԓGSан
2571       лэGSлфԓэʔԓкас
3180        ноGSӈӄаʔԓкас
3181         ноGSӈӄаʔԓэс
3269       нәлкәGSлэʔԓэс
5647       ӽэGSлучэʔԓкас
5903        чэGSнӈэʔԓкас
6975        элGSэлэʔԓкас
Name: entry, dtype: str

На конце слова:

In [11]:
iavd_words_with_gs_corrected.str.endswith('ʔ').sum() / LEN

np.float64(0.09610983981693363)

Остальные:

In [303]:
iavd_words_with_gs_corrected[~(iavd_words_with_gs_corrected.str.endswith('ʔ') | iavd_words_with_gs_corrected.str.contains('ʔԓ') | iavd_words_with_gs_corrected.str.contains('ʔ[аиуоәэые]') | iavd_words_with_gs_corrected.str.contains('ʔ[нймњӈлрљв]'))]

486      ӑӈӄанэʔсх
1175       исхэʔсх
1400        каʔкас
1913        кэʔкʼф
2064       кʼэʔкас
2127          ӄаʔт
2128     ӄаʔт итʼэ
2129         ӄаʔтх
2130     ӄаʔтʼанан
2246      ӄәнʔтʼсх
2389     лаӽсхэʔсх
2392     лаӽсӽэʔсх
2558     лэӽсӽэʔсх
3331     нэԓʔчалас
3596       оʔтэкас
4664    толкʼаʔкас
4694        тоʔсэс
5644       ӽэʔӄʼԓх
6878     әӈӄанэʔсх
2131      ӄаʔтGSин
Name: entry, dtype: str

### Не встречается ни разу с

In [ ]:
# создаем набор символов
chars_vocab = set()
for entry in iavd['entry']:
    chars_vocab.update(set(entry))

chars_vocab = chars_vocab - set(punctuation) - set((' ', '˚', 'ь', 'ъ', 'ʼ', '̆')) # убираем явно нерелевантные символы

# правый контекст
print('Правый контекст: ', end='')
for char in chars_vocab:
    if iavd_words_with_gs_corrected.str.contains(f'ʔ{char}').sum() == 0:
        print(char, end=', ')

print()

# левый контекст
print('Левый контекст: ', end='')
for char in chars_vocab:
    if iavd_words_with_gs_corrected.str.contains(f'{char}ʔ').sum() == 0:
        print(char, end=', ')

Правый контекст: ё, д, г, ж, з, ф, щ, п, ы, ӽ, ӑ, ŏ, е, ц, c, ш, ў, ʔ, я, б, ю, х,
Левый контекст: ё, д, г, ж, щ, п, ӑ, ŏ, е, ц, њ, c, ӄ, ш, ў, ʔ, я, б, ю,

In [13]:
r = set(('д', 'х', 'п', 'б', 'з', 'ц', 'ʔ', 'ю', 'ӽ', 'ш', 'ў', 'щ', 'е', 'ф', 'г', 'ŏ', 'ж', 'ы', 'ё', 'я', 'ӑ'))
l = set(('д', 'ӄ', 'п', 'б', 'ц', 'ʔ', 'ю', 'ш', 'ў', 'щ', 'е', 'г', 'ŏ', 'њ', 'ж', 'ё', 'я', 'ӑ'))
l - r, r - l

({'њ', 'ӄ'}, {'з', 'ф', 'х', 'ы', 'ӽ'})

с лишнее -- оно латинское:

In [14]:
iavd[iavd['entry'].str.contains('c')]

           entry                 link
269     анʔавнаc  /dictionary/ru/8747
844  зәмчʼсхэнәc  /dictionary/ru/3122

Абруптивы (они двумя символами):

In [80]:
iavd[iavd['entry'].str.contains('ʼʔ')]

       entry                  link
1229  ичʼʔин  /dictionary/ru/13560

In [ ]:
iavd[iavd['entry'].str.contains('ʔ.ʼ')]

          entry                  link
1913     кэʔкʼф   /dictionary/ru/9728
2130  ӄаʔтʼанан   /dictionary/ru/5325
2246   ӄәнʔтʼсх  /dictionary/ru/14830
5644    ӽэʔӄʼԓх  /dictionary/ru/12489

### Что перед гортанной смычкой

Сонанты:

In [ ]:
iavd_words_with_gs_corrected.str.contains('[нймњӈлрљв]ʔ').sum() / LEN

np.float64(0.06864988558352403)

Гласные:

In [ ]:
iavd_words_with_gs_corrected.str.contains('[аиуоәэые]ʔ').sum() / LEN

np.float64(0.8546910755148741)

Начало:

In [16]:
iavd_words_with_gs_corrected[iavd_words_with_gs_corrected.str.startswith('ʔ')] # но по словарю это морфема

7265    ʔин
Name: entry, dtype: str

Остальное:

In [ ]:
iavd_words_with_gs_corrected[iavd_words_with_gs_corrected.str.contains('[^аиуоәэыенймњӈлрљв]ʔ')]

359             асʔамԓкас
360                 асʔас
413               атхʔатх
414            атхʔатхчан
1214              ифԓӽʔин
1219              иӽԓӽʔин
1229               ичʼʔин
1411           кӑннэнхʔал
1476             ккаӈԓʔан
1481              клачʔин
1484              клыԓʔин
1512             кԓмаԓʔан
1519            кԓфањчʔан
1530            кԓфәњчʔан
1768              куԓӽʔин
1794           кӽаӄањԓʔин
1796             кчинзʔин
1804               кчфʔин
1852          кәнннэнхʔал
1950            кʼилфсʔин
2066             кʔэнэзэс
2149               ӄиӽʔин
2234     ӄуфсизʔин кивэчӽ
2376              ламԓʔан
2485        лыԓи ксуњԓʔин
2587             љэњиԓʔан
2632              ԓваԓʔан
2949              манхʔал
2981             мимсхʔин
2992              мныԓʔан
3063            мэчʼахʔал
3234             ныныԓʔан
3331            нэԓʔчалас
3368        ӈимсхʔин пʼэч
3725               пԓӽʔин
3998              салхʔал
4102         сичʼэӈанхʔал
4419              сэнхʔал
4423             сэњчхʔал
4604             тмалхʔал
4620             тнўмхʔал
4691              тосхʔан
4843                тхʔал
5070             тʼаԓхʔал
5071              тʼаԓʔан
5216              утхʔутх
5386              ханхʔал
5391             хањчхʔал
5392              хањчʔан
5480           хтоӈанхʔал
5523            хэԓваԓʔан
5598               ӽохʔал
5782               чԓхʔин
5862              чәсхʔал
5935           чʼаӽлэзʔан
6139               әлхʔэс
7183            этӽʔэлкас
178     аназʔан ӈэззэGSњч
1551          кԓʔасаӈаGSн
1414      кбарабанэGSԓʔан
1503          кљэчэGSԓʔин
1808           кчʼэGSԓʔин
1931         кʼансэGSԓʔан
1932     кʼанхтʼԓӈаGSԓʔан
1933        кʼанхчоGSԓʔан
2131             ӄаGSтʔин
Name: entry, dtype: str

Два х:

In [ ]:
iavd_words_with_gs_corrected.str.contains('[хӽ]ʔ').sum()

np.int64(31)

Два х и не суффикс исходно-продольного падежа:

In [74]:
iavd_words_with_gs_corrected[iavd_words_with_gs_corrected.str.contains('[хӽ]ʔ') & ~iavd_words_with_gs_corrected.str.endswith('хʔал')]

413           атхʔатх
414        атхʔатхчан
1214          ифԓӽʔин
1219          иӽԓӽʔин
1768          куԓӽʔин
2149           ӄиӽʔин
2981         мимсхʔин
3368    ӈимсхʔин пʼэч
3725           пԓӽʔин
4691          тосхʔан
5216          утхʔутх
5782           чԓхʔин
6139           әлхʔэс
7183        этӽʔэлкас
Name: entry, dtype: str

ԓ:

In [54]:
iavd_words_with_gs_corrected[iavd_words_with_gs_corrected.str.contains('ԓʔ')]

1476            ккаӈԓʔан
1484             клыԓʔин
1512            кԓмаԓʔан
1794          кӽаӄањԓʔин
2376             ламԓʔан
2485       лыԓи ксуњԓʔин
2587            љэњиԓʔан
2632             ԓваԓʔан
2992             мныԓʔан
3234            ныныԓʔан
3331           нэԓʔчалас
5071             тʼаԓʔан
5523           хэԓваԓʔан
1551         кԓʔасаӈаGSн
1414     кбарабанэGSԓʔан
1503         кљэчэGSԓʔин
1808          кчʼэGSԓʔин
1931        кʼансэGSԓʔан
1932    кʼанхтʼԓӈаGSԓʔан
1933       кʼанхчоGSԓʔан
Name: entry, dtype: str

Остальное без двух х и ԓ:

In [ ]:
iavd_words_with_gs_corrected[iavd_words_with_gs_corrected.str.contains('[^аиуоәэыенймњӈлрљвхӽԓ]ʔ')]

359             асʔамԓкас
360                 асʔас
1229               ичʼʔин
1481              клачʔин
1519            кԓфањчʔан
1530            кԓфәњчʔан
1796             кчинзʔин
1804               кчфʔин
1950            кʼилфсʔин
2066             кʔэнэзэс
2234     ӄуфсизʔин кивэчӽ
5392              хањчʔан
5935           чʼаӽлэзʔан
178     аназʔан ӈэззэGSњч
2131             ӄаGSтʔин
Name: entry, dtype: str

### Или

In [309]:
iavd_words_with_gs[iavd_words_with_gs.str.contains('[^аиуоәэые]ʔ[^аиуоәэые]')]

142      амамʔйоӄ
2246     ӄәнʔтʼсх
3331    нэԓʔчалас
Name: entry, dtype: str